### ISSUE TITLE
How to pass extra parameters while starting the appium server?

### ISSUE THREAD

**Issue by rahulmr** [aaronbriel/appium-controller#2]
Hello @aaronbriel ,
First of all thanks for this wonderful utility which works out of the box on Mac and Windows.
This is very useful for me.

I have just upgraded to `appium 1.7.1` and there seems to some deprecated args and a new arg which can be passed to `appium` while starting the appium server.
This is ` --default-capabilities `, could you please let me know how this can be in the `appium-controller` utility?

Also, I wanted to know how to make appium work only for a specific device based on its name (in case I don't want to use the `udid` parameter)

I have a situation in which there are 2 devices connected to the Mac Mini and I want to run my tests only on 1 device. Currently I am using `wdio` runner and `wdio-appium-service` to run my tests, but the tests are running on the unwanted device instead of the desired one.

Thanks in advance for your urgent help :)

**Comment by aaronbriel** [comment]
Hello @rahulmr , 

My apologies for the delay on this - I was out of town. I have added the --default-capabilities option, which can be specified in a method call or on the command line using 'defaultCapabilities' or the '--dc' shortcut. 

Please re-open this if you see any issues with the fix.

**Comment by kirilpo** [comment]
Hi guys, 

I am new using  appium-controller. I was about to start appium as a node in grid, but seems like I cannot get the --nodeconfig flag to pass json file with caps + node config.
Any workaround, or fix?

**Comment by aaronbriel** [comment]
@kirilpo I no longer have time to maintain this package, but adding the --nodeconfig command line option should be very similar to [the commit for this fix](https://github.com/aaronbriel/appium-controller/commit/0d4f17c6ef4d8640d15379606772368782ac13b5). Feel free to create a PR with this fix.
